WITH MAX_REVIEWERS AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(REVIEW_COUNT)
        FROM (SELECT COUNT(*) AS REVIEW_COUNT
              FROM REST_REVIEW
              GROUP BY MEMBER_ID
             ) AS REVIEW_COUNTS
    )
)
SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW R
JOIN
    MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
JOIN
    MAX_REVIEWERS MR ON R.MEMBER_ID = MR.MEMBER_ID
ORDER BY
    REVIEW_DATE ASC,
    REVIEW_TEXT ASC